New Features
MikeyUsersREC/ERM pull request #110
Opened 2024-11-22 06:08 UTC by shashankpandey04

- Allow admin roles to accept LOAs
- Advance LOAs
- LOA View Command
- Custom Command Embed Edit

2024-11-22 08:16 UTC, shashankpandey04 commented
- Automatic Kick/Ban Logging
- Bug Fixes

2024-11-22 08:17 UTC, shashankpandey04 commented
-Automatic pm to users, if not found in Discord Server

2024-11-23 12:49 UTC, shashankpandey04 commented
- Punishment Alert: New appeal moderation button whenever user gets a punishment alert from ERM.
- Fixed Shift Report: Now shift report will show total moderations you made during shift.

2024-11-30 13:05 UTC, MikeyUsersREC requested changes
requesting changes
see comments for details

2024-11-30 13:05 UTC, mikeywhiston commented on .env.template
good

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/ActivityNotices.py
im fine with the /loa view, /ra view stuff
but, you cant have an ephemeral paginator; so you have to pick one or the other
i found this out the hard way with the paginator being broken on /loa active for a long time so we had to scrap the ephemeral part of it

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/ActivityNotices.py
you might wanna add an exception handler to `starting`, just in case people put like 21/10/2024 or smth

2024-11-30 13:05 UTC, mikeywhiston commented on menus.py
why do we need to change `CustomCommandModification` to `CustomCommandModificationEdit`
why do we need to change `MessageCustomisation` to `MessageCustomisationEdit`
whats the benefit here?

2024-11-30 13:05 UTC, mikeywhiston commented on utils/utils.py
ok so first of all; i like what you did with the sub_vars on the fields

however, for `run_pm_command`:
- **there is no retry-after header** | see the [**actual api docs**](https://apidocs.policeroleplay.community)
- even if there was one, you have to do `ResetTime - CurrentTime` to get the time to wait for, instead of just waiting on the `ResetTime` which would cause a wait period of 11291 years if i recall correctly

2024-11-30 13:05 UTC, mikeywhiston commented on events/on_shift_end.py
this should be fine

2024-11-30 13:05 UTC, mikeywhiston commented on events/on_punishment.py
this
```py
view.add_item(discord.ui.Button(label="Appeal Moderation", url=f"https://ermbot.xyz/{guild.id}/{warning.snowflake}/appeal"))
```
is **not** a supported feature

2024-11-30 13:05 UTC, mikeywhiston commented on events/on_message.py
no??!! 
why are you replacing the erm remote command functionality with the autologging channel?
you need two separate if statements for the two features, not just interchangeably replace them

2024-11-30 13:05 UTC, mikeywhiston commented on erm.py
for whitelisted car functionality, cant you just search through the people who hold the exotic car roles instead of `guild.members`?

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/ShiftLogging.py
not sure how i feel about adding the count of moderations to each item on the shift leaderboard
i mean, thats what the google spreadsheet is for
ask erm team ig

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/Punishments.py
yeah ok good
you actually followed through on what i said

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/ShiftLogging.py
so i just asked in erm team and they suggested we move it to a `/punishment leaderboard` where its sorted by moderations

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/CustomCommands.py
still dont know why we need to replace `CustomCommandModification` with `CustomCommandModificationEdit`

2024-11-30 13:05 UTC, mikeywhiston commented on cogs/ERLC.py
i mean, simplifying the regex to a kv dict ` { name | display | global: member } ` doesnt sound like that bad of an idea in retrospect
but, two people can have the same display, name, or global name, and then it'd replace the person in the dictionary with that
just something to consider

2024-12-03 05:34 UTC, shashankpandey04 commented on menus.py
`CustomCommandModification` and `MessageCustomisation` doesn't directly support the Embed Customization by default. So instead of modifying existing functions I modified the UI and added the functionality to edit Embeds in different class to prevent any errors in existing custom command creation.

2024-12-03 05:55 UTC, shashankpandey04 commented on events/on_message.py
`Line 200:` This checks if server has enabled Remote Command and setup the Auto Logging Channel to automatically log Kick/Ban.

`Line 274:` This is the line which goes for Remote Commands, there was a typo which I noticed later due to which there were two different remote command execution but due to different functionality of login only the remote command condition was working.

2024-12-03 05:56 UTC, shashankpandey04 commented on erm.py
```role_based_users = {}
                for role in exotic_roles:
                    role_based_users[role] = [member for member in role.members if member.guild == guild]
                for role, member in role_based_users.items():```
 Updated to `role.members` as this would be a better approach in this case reducing the time complexity.

2024-12-03 05:57 UTC, shashankpandey04 commented on cogs/ShiftLogging.py
Fixed 👍

2024-12-03 06:19 UTC, shashankpandey04 commented on cogs/ERLC.py
Fixed 👍 
Suppose you have three members:
Quprgaming
quprgaming
Bajah with a global name of Rajah
Then,
```{
    'quprgaming': [member1, member2], 
    'bajah': [member3], 
    'Rajah': [member3] 
}```

Then the condition 
`if player_username_lower in guild_members_dict and guild_members_dict[player_username_lower]:`
Will check if the user is in guild members and present in that name key of guild member.
This will avoid the confusion between different members with same name.

2024-12-03 06:20 UTC, shashankpandey04 commented on events/on_punishment.py
Fixed, will be added back once Noah has appeal system done 👍

2024-12-03 12:19 UTC, shashankpandey04 commented
- Fixed ERM Link Command 👍 
- Added Permission Mapping Function and predicate for Module Based Permissions (will be implemented in future)

2024-12-28 04:36 UTC, shashankpandey04 commented
Tried to fix the Player Join Logs getting sent again every time bot restarts.

2024-12-29 00:01 UTC, MikeyUsersREC commented on erm.py
instead of a 10 minute intermediate time for process_player_logs; if you want to check if the bot has restarted since the log, you should compare `log.timestamp < bot.start_time` which is used by uptime as the bot startup time.

2024-12-29 00:02 UTC, MikeyUsersREC commented on cogs/ERLC.py
good!

2024-12-29 00:02 UTC, MikeyUsersREC commented on utils/utils.py
so um... blame prc? they added this header without ever putting it on the docs and i've been saying it doesnt exist for months 💀

2024-12-29 00:03 UTC, MikeyUsersREC commented on menus.py
MessageCustomisation doesnt support EmbedCustomisation because it subclasses EmbedCustomisation in the "Add Embed" function

if you want to edit embeds, you should use EmbedCustomisation

2025-01-03 07:46 UTC, shashankpandey04 commented
- Automated Discord Checks Task

2025-01-03 17:25 UTC, NoahCxrest commented on tasks/discord_checks.py
lgtm. add more configuration though like in discord_checks they should be able to do the following:
```
{
	"discord_checks": {
		"channel": 0, // Where to send discord check results to
		"should_load": bool, // Should it load them or kick them?
		"should_warn": bool, // Should it give them a PM Warning?
		"kick_after_infractions": 0, // How many loads (if loading is on), or warnings if its not, should the user get before they're kicked?
		"message": "str", // What message should it send the user?
		"mentioned_roles": [ // What roles should be mentioned in the channel?
			0
			1
			2
			3
		]
	}
}
```

2025-01-11 04:53 UTC, shashankpandey04 commented
- Enhanced Automated Discord Check
- Enhanced Automated Vehicle Check

2025-01-11 05:42 UTC, shashankpandey04 commented
Fixed Automatic Shifts 🕺

2025-01-29 13:52 UTC, shashankpandey04 commented
Updated ER:LC Integration Configuration UI

2025-01-30 03:50 UTC, shashankpandey04 commented
**Duty Admin Abuse Prevention**
- Shift End
  - From now Guild Name will be sent in Shift Report if admin manipulates staff without user acknowledgement.
  - As some users were reporting about their shift ending from some server but had no idea from which server it was.
- Duty Admin
  - Now staff will get DM as soon someone adds/subtracts shift time in their shift to prevent admin abuse.
  - This may fix the issue of repeated admin abuse in servers.

2025-03-10 06:30 UTC, closed without merging