Updated Auto Kick/Ban Logging
MikeyUsersREC/ERM pull request #87
Opened 2024-08-01 17:22 UTC by shashankpandey04

2024-08-03 01:51 UTC, NoahCxrest approved these changes
Approved

2024-08-05 03:27 UTC, MikeyUsersREC commented on cogs/ActivityNotices.py
**[ DO NOT PUSH ]**
RA Requests will not work with this change.

2024-08-05 03:34 UTC, MikeyUsersREC requested changes
See comments for details.

2024-08-05 03:34 UTC, MikeyUsersREC commented on cogs/ActivityNotices.py
**[ DO NOT PUSH ]**
RA Requests will not work with this change.

2024-08-05 03:34 UTC, MikeyUsersREC commented on cogs/CustomCommands.py
Line 325-330 doesn't fix the underlying issues if ['message'] is none.

2024-08-05 03:34 UTC, MikeyUsersREC commented on cogs/Punishments.py
"Management" here refers to a shorthand of "Punishment Management", not "Management" as a permission level.

2024-08-05 03:34 UTC, MikeyUsersREC commented on erm.py
I have no problem with line 154.

713-740 **should not** be in the main erm file. This is meant to be a file to be loaded before everything else. Specific utilities should be modularised in the utils folder. `utils/utils.py` would be a better destination. Also change the name of the `run_command` function here to something more related to its scope - as it'd be confused with `PRCApiClient.run_command`

2024-08-05 03:34 UTC, MikeyUsersREC commented on menus.py
I have some problems with Line 6905, and similar.

Data schemes should always be present in the dataset. We shouldn't have values that don't exist, as that would make our data schema less clean. All values should be present, as with most of the newer modules.

2024-08-05 04:39 UTC, closed without merging