Bug Fixes and DB Schema Fix
MikeyUsersREC/ERM pull request #93
Opened 2024-08-14 12:48 UTC by shashankpandey04

- Fixed Shift Report
- Attempt to fix Whitelisted Vehicle Check
- Duty Manage showing Total Time according to Shift Type now.
- Added new `/duty history` command to see past shifts.

2024-08-14 13:27 UTC, shashankpandey04 commented
- Fixed ERLC Statistics Module

2024-08-18 04:47 UTC, shashankpandey04 commented
Updated **ERLC.py**
- Tried to fix the Multiline Command Log breaking the ERM Embed.

2024-08-18 05:15 UTC, shashankpandey04 commented
- Added Personal Message Support to the in-game players who were not found in discord server.
- 1 minute cooldown in `/erlc check` command for each guild to avoid spam.
- Customizable Message from `/config > ER:LC Integration > More Features > Discord Check Message`

2024-08-19 05:54 UTC, shashankpandey04 commented
- Fixed Player Join/Leave Logs
- Fixed Kill Logs

2024-08-21 07:16 UTC, shashankpandey04 commented
- Added New Feature
  - Custom Command Embed Edit

2024-08-28 03:09 UTC, MikeyUsersREC requested changes
more changes required for push

2024-08-28 03:09 UTC, mikeywhiston commented on .env.template
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on cogs/ActivityNotices.py
Why the fuck has bro doccstringed an entire subcommand
464->527: lgtm
646->728: wtf

Furthermore, you somehow forgot that RA even existed. You made changes to the LOA request command signature however you did not parity that to RA system.

2024-08-28 03:09 UTC, mikeywhiston commented on cogs/ERLC.py
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on cogs/CustomCommands.py
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on cogs/Punishments.py
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on cogs/ShiftLogging.py
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on erm.py
L648:L657: please learn what dict.get() is
L709:L716: this is a lot of is statements, probably better to turn it more pythonic
@NoahCxrest -> look at L690; could be the CPU leak

2024-08-28 03:09 UTC, MikeyUsersREC commented on events/on_message.py
iirc `kick_ban_webhook_channel` is a variable instantiated by game security to detect if 25 people were kicked and to activate mass aa. not a good idea to reuse variables for auto_kick_ban

2024-08-28 03:09 UTC, MikeyUsersREC commented on events/on_shift_end.py
lgtm

2024-08-28 03:09 UTC, mikeywhiston commented on events/on_punishment.py
lgtm

2024-08-28 03:09 UTC, MikeyUsersREC commented on menus.py
lgtm

2024-08-28 03:09 UTC, MikeyUsersREC commented on menus.py
please start using dict.get() instead of `string in dict`. it is better practise to use dict.get()!!!

2024-08-28 03:09 UTC, mikeywhiston commented on utils/utils.py
lgtm

2024-08-28 03:09 UTC, MikeyUsersREC commented on utils/prc_api.py
is this really a good idea tho?
also iirc its not retry-after
see https://api-docs.policeroleplay.community for details

2024-08-28 03:09 UTC, MikeyUsersREC commented on utils/prc_api.py
https://apidocs.policeroleplay.community

2024-08-29 15:24 UTC, shashankpandey04 commented on cogs/ActivityNotices.py
The `core_command_view` was developed to allow staff to view and request the end or extension of their ongoing LOA/RA. This functionality is already available to the Management team. Adding these features for staff will eliminate the primary purpose of the LOA Admin Command, which is why the command has not been removed but is being retained as a precaution for future needs.

2024-08-29 15:24 UTC, shashankpandey04 commented on utils/prc_api.py
Yes, most likely. If we encounter rate limiting, we can retry the request after the required time. Implementing the retry logic in the main function would be more efficient than adding it to each function that relies on the main one. This approach ensures consistency and reduces redundancy.

Additionally, the header has been updated to `X_RateLimit_Reset` in accordance with the PRC API Headers. With this approach, we can also address issues with Join/Leave and Player Kill Logs effectively.

2024-08-29 15:24 UTC, shashankpandey04 commented on events/on_message.py
Fixed

2024-08-30 01:20 UTC, MikeyUsersREC commented on utils/prc_api.py
Did you get ChatGPT to read the docs?
It literally says in the docs the header that shows you the timestamp when it resets.
Also, the header is a TIMESTAMP, not even an amount of seconds.

2024-08-30 01:21 UTC, MikeyUsersREC requested changes

2024-08-30 01:21 UTC, MikeyUsersREC commented on utils/prc_api.py
X-RateLimit-Reset is a timestamp.

2024-08-30 04:39 UTC, shashankpandey04 commented on utils/prc_api.py
Fixed

2024-09-25 23:14 UTC, MikeyUsersREC requested changes
please dont autoapprove :(

2024-09-25 23:14 UTC, mikeywhiston commented on cogs/ActivityNotices.py
You still haven't changed what I said.
Do not doccstring a command. Comment it out or remove it.

2024-09-25 23:14 UTC, MikeyUsersREC commented on utils/prc_api.py
It's a timestamp. ..
I told you this about 6 times. ..
It's a timestamp... 

If this got posted to production, each server would wait up to 19991 days for their command to be sent!
`asyncio.sleep(datetime.datetime.now().timestamp() - response.headers.get('X_RateLimit_Reset'+1, datetime.datetime.now().timestamp() + 5))`

2024-09-30 08:26 UTC, shashankpandey04 commented
- Added LOA/RA View Command

2024-10-08 20:13 UTC, MikeyUsersREC requested changes
new changes required
good luck

2024-10-08 20:13 UTC, MikeyUsersREC commented on utils/prc_api.py
asyncio.sleep is a coroutine - await is required

2024-10-08 20:13 UTC, MikeyUsersREC commented on cogs/ActivityNotices.py
ideally core_command_view should return ephemeral for interaction contexts
if ctx.interaction: respond ephemerally (actually test this!)
if not ctx.interaction: respond regularly

2024-10-11 09:08 UTC, shashankpandey04 commented on cogs/ActivityNotices.py
`ctx.interaction.response.send_message` is throwing "This interaction has already responded", added under `try/expect` block just in case `ctx.interaction` updated in future.

2024-10-13 06:33 UTC, shashankpandey04 commented
- Fixed Custom Run:
The custom run was not updating the variables in the embed fields due to the EmbedField object being read-only. And trying to update the fields directly would result in an Attribute Error. To resolve this, we store the EmbedField objects in a temporary storage, which allows us to update the field values with the variable data. We can then add the updated fields to the embed without encountering any errors.

2024-11-09 08:21 UTC, closed without merging